= Discussion Paper template in Metanorma

== General

The document structure is modeled after that of an OGC standard, however, you may change or remove sections as you need to best construct a Discussion Paper.


== Content

This folder contains the text for the Discussion Paper

* `document.adoc` - the main Discussion Paper document with references to all sections
* remaining ``adoc``s - each section of the Discussion Paper document is in a separate document: follow directions in each document to populate
* `figures` - figures go here
* `images` - Image files for graphics go here. Image files for figures go in the `figures` directory. Only place in here images not used in figures (e.g., as parts of tables, as logos, etc.)
* `requirements` - (OPTIONAL) directory for requirements and requirement classes to be referenced in `clause_7_normative_text.adoc`
* `code` - (OPTIONAL) sample code to accompany the Discussion Paper, if desired
* `abstract_tests` - (OPTIONAL) the Abstract Test Suite comprising one test for every requirement, optional
* `UML` - UML diagrams, if applicable

== Building

To convert the draft OGC Discussion Paper from asciidoc format to HTML and PDF formats, we use the metanorma software to **compile** the document.

From this folder, run the following command.

`docker run -v "$(pwd)":/metanorma -v ${HOME}/.fontist/fonts/:/config/fonts  metanorma/mn  metanorma compile --agree-to-terms -t ogc -x xml,html,doc document.adoc`
